//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public string AccountNumber { get; set; }
        public decimal Balance { get; set; }
        public int Bonus { get; set; }
        public bool Closed { get; set; }
        public int ClientId { get; set; }
        public int AccountTypeId { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual Client Client { get; set; }
    }
}
